name: Publish images to Docker Hub
on: [workflow_dispatch]

jobs:
  # publish_sonos_api:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3
  #     - name: build
  #       run: |
  #         docker build -t mattmagin/sonos-http-api:latest ./sonos-http-api
  #     - name: publish
  #       run: |
  #         docker push mattmagin/sonos-http-api:latest

  publish_music_player:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build
        run: |
          docker build -t mattmagin/music-player:latest ./music-player
      - name: publish
        run: |
          docker push mattmagin/music-player:latest
