name: Publish Music Player Image to Docker Hub
on:
  push:
    branches:
      - main
      paths:
        - "music-player/**"
    workflow_dispatch:

jobs:
  publish_music_player:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build
        run: |
          docker build -t mattmagin/music-player:latest ./music-player
      - name: publish
        run: |
          docker push mattmagin/music-player:latest
